#!/usr/bin/env bash
#comment
PIDFILE="/tmp/myscript.pid"  # /var/run/ əvəzinə /tmp istifadə

# PID faylını yaz
echo $$ > "$PIDFILE"

# SIGTERM zamanı
trap 'echo "I hate the kill command"; rm -f "$PIDFILE"; exit 0' SIGTERM

# SIGINT (Ctrl+C)
trap 'echo "Y U no love me?!";' SIGINT

# SIGQUIT
trap 'rm -f "$PIDFILE"; exit 0' SIGQUIT

# Sonsuz loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
