#!/usr/bin/env bash
#This script manages the process using arguments such as start, stop, and restart
PIDFILE="/var/run/my_process.pid"
case "$1" in 
	start) 
		mkdir -p /var/run 2>/dev/null
		./manage_my_process &
		echo "$!" > "$PIDFILE"
		echo 'manage_my_process started'
		;;
	stop)
		killall manage_my_process
		rm "$PIDFILE"
		echo 'manage_my_process stopped'
		;;
	restart)
		killall manage_my_process
		rm "$PIDFILE"
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo 'manage_my_process restarted'
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
		exit 1
		;;
esac
